
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PackImage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PackImage
 * 
 */
export type PackImageModel = runtime.Types.Result.DefaultSelection<Prisma.$PackImagePayload>

export type AggregatePackImage = {
  _count: PackImageCountAggregateOutputType | null
  _avg: PackImageAvgAggregateOutputType | null
  _sum: PackImageSumAggregateOutputType | null
  _min: PackImageMinAggregateOutputType | null
  _max: PackImageMaxAggregateOutputType | null
}

export type PackImageAvgAggregateOutputType = {
  weight: number | null
}

export type PackImageSumAggregateOutputType = {
  weight: number | null
}

export type PackImageMinAggregateOutputType = {
  id: string | null
  packId: string | null
  imageId: string | null
  weight: number | null
}

export type PackImageMaxAggregateOutputType = {
  id: string | null
  packId: string | null
  imageId: string | null
  weight: number | null
}

export type PackImageCountAggregateOutputType = {
  id: number
  packId: number
  imageId: number
  weight: number
  _all: number
}


export type PackImageAvgAggregateInputType = {
  weight?: true
}

export type PackImageSumAggregateInputType = {
  weight?: true
}

export type PackImageMinAggregateInputType = {
  id?: true
  packId?: true
  imageId?: true
  weight?: true
}

export type PackImageMaxAggregateInputType = {
  id?: true
  packId?: true
  imageId?: true
  weight?: true
}

export type PackImageCountAggregateInputType = {
  id?: true
  packId?: true
  imageId?: true
  weight?: true
  _all?: true
}

export type PackImageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PackImage to aggregate.
   */
  where?: Prisma.PackImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackImages to fetch.
   */
  orderBy?: Prisma.PackImageOrderByWithRelationInput | Prisma.PackImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PackImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PackImages
  **/
  _count?: true | PackImageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PackImageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PackImageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PackImageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PackImageMaxAggregateInputType
}

export type GetPackImageAggregateType<T extends PackImageAggregateArgs> = {
      [P in keyof T & keyof AggregatePackImage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePackImage[P]>
    : Prisma.GetScalarType<T[P], AggregatePackImage[P]>
}




export type PackImageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PackImageWhereInput
  orderBy?: Prisma.PackImageOrderByWithAggregationInput | Prisma.PackImageOrderByWithAggregationInput[]
  by: Prisma.PackImageScalarFieldEnum[] | Prisma.PackImageScalarFieldEnum
  having?: Prisma.PackImageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PackImageCountAggregateInputType | true
  _avg?: PackImageAvgAggregateInputType
  _sum?: PackImageSumAggregateInputType
  _min?: PackImageMinAggregateInputType
  _max?: PackImageMaxAggregateInputType
}

export type PackImageGroupByOutputType = {
  id: string
  packId: string
  imageId: string
  weight: number
  _count: PackImageCountAggregateOutputType | null
  _avg: PackImageAvgAggregateOutputType | null
  _sum: PackImageSumAggregateOutputType | null
  _min: PackImageMinAggregateOutputType | null
  _max: PackImageMaxAggregateOutputType | null
}

type GetPackImageGroupByPayload<T extends PackImageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PackImageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PackImageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PackImageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PackImageGroupByOutputType[P]>
      }
    >
  >



export type PackImageWhereInput = {
  AND?: Prisma.PackImageWhereInput | Prisma.PackImageWhereInput[]
  OR?: Prisma.PackImageWhereInput[]
  NOT?: Prisma.PackImageWhereInput | Prisma.PackImageWhereInput[]
  id?: Prisma.StringFilter<"PackImage"> | string
  packId?: Prisma.StringFilter<"PackImage"> | string
  imageId?: Prisma.StringFilter<"PackImage"> | string
  weight?: Prisma.IntFilter<"PackImage"> | number
  pack?: Prisma.XOR<Prisma.PackScalarRelationFilter, Prisma.PackWhereInput>
  image?: Prisma.XOR<Prisma.ImageScalarRelationFilter, Prisma.ImageWhereInput>
}

export type PackImageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  packId?: Prisma.SortOrder
  imageId?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  pack?: Prisma.PackOrderByWithRelationInput
  image?: Prisma.ImageOrderByWithRelationInput
}

export type PackImageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  packId_imageId?: Prisma.PackImagePackIdImageIdCompoundUniqueInput
  AND?: Prisma.PackImageWhereInput | Prisma.PackImageWhereInput[]
  OR?: Prisma.PackImageWhereInput[]
  NOT?: Prisma.PackImageWhereInput | Prisma.PackImageWhereInput[]
  packId?: Prisma.StringFilter<"PackImage"> | string
  imageId?: Prisma.StringFilter<"PackImage"> | string
  weight?: Prisma.IntFilter<"PackImage"> | number
  pack?: Prisma.XOR<Prisma.PackScalarRelationFilter, Prisma.PackWhereInput>
  image?: Prisma.XOR<Prisma.ImageScalarRelationFilter, Prisma.ImageWhereInput>
}, "id" | "packId_imageId">

export type PackImageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  packId?: Prisma.SortOrder
  imageId?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  _count?: Prisma.PackImageCountOrderByAggregateInput
  _avg?: Prisma.PackImageAvgOrderByAggregateInput
  _max?: Prisma.PackImageMaxOrderByAggregateInput
  _min?: Prisma.PackImageMinOrderByAggregateInput
  _sum?: Prisma.PackImageSumOrderByAggregateInput
}

export type PackImageScalarWhereWithAggregatesInput = {
  AND?: Prisma.PackImageScalarWhereWithAggregatesInput | Prisma.PackImageScalarWhereWithAggregatesInput[]
  OR?: Prisma.PackImageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PackImageScalarWhereWithAggregatesInput | Prisma.PackImageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PackImage"> | string
  packId?: Prisma.StringWithAggregatesFilter<"PackImage"> | string
  imageId?: Prisma.StringWithAggregatesFilter<"PackImage"> | string
  weight?: Prisma.IntWithAggregatesFilter<"PackImage"> | number
}

export type PackImageCreateInput = {
  id?: string
  weight?: number
  pack: Prisma.PackCreateNestedOneWithoutPackImagesInput
  image: Prisma.ImageCreateNestedOneWithoutPackImagesInput
}

export type PackImageUncheckedCreateInput = {
  id?: string
  packId: string
  imageId: string
  weight?: number
}

export type PackImageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
  pack?: Prisma.PackUpdateOneRequiredWithoutPackImagesNestedInput
  image?: Prisma.ImageUpdateOneRequiredWithoutPackImagesNestedInput
}

export type PackImageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  packId?: Prisma.StringFieldUpdateOperationsInput | string
  imageId?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackImageCreateManyInput = {
  id?: string
  packId: string
  imageId: string
  weight?: number
}

export type PackImageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackImageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  packId?: Prisma.StringFieldUpdateOperationsInput | string
  imageId?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackImageListRelationFilter = {
  every?: Prisma.PackImageWhereInput
  some?: Prisma.PackImageWhereInput
  none?: Prisma.PackImageWhereInput
}

export type PackImageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PackImagePackIdImageIdCompoundUniqueInput = {
  packId: string
  imageId: string
}

export type PackImageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  packId?: Prisma.SortOrder
  imageId?: Prisma.SortOrder
  weight?: Prisma.SortOrder
}

export type PackImageAvgOrderByAggregateInput = {
  weight?: Prisma.SortOrder
}

export type PackImageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  packId?: Prisma.SortOrder
  imageId?: Prisma.SortOrder
  weight?: Prisma.SortOrder
}

export type PackImageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  packId?: Prisma.SortOrder
  imageId?: Prisma.SortOrder
  weight?: Prisma.SortOrder
}

export type PackImageSumOrderByAggregateInput = {
  weight?: Prisma.SortOrder
}

export type PackImageCreateNestedManyWithoutImageInput = {
  create?: Prisma.XOR<Prisma.PackImageCreateWithoutImageInput, Prisma.PackImageUncheckedCreateWithoutImageInput> | Prisma.PackImageCreateWithoutImageInput[] | Prisma.PackImageUncheckedCreateWithoutImageInput[]
  connectOrCreate?: Prisma.PackImageCreateOrConnectWithoutImageInput | Prisma.PackImageCreateOrConnectWithoutImageInput[]
  createMany?: Prisma.PackImageCreateManyImageInputEnvelope
  connect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
}

export type PackImageUncheckedCreateNestedManyWithoutImageInput = {
  create?: Prisma.XOR<Prisma.PackImageCreateWithoutImageInput, Prisma.PackImageUncheckedCreateWithoutImageInput> | Prisma.PackImageCreateWithoutImageInput[] | Prisma.PackImageUncheckedCreateWithoutImageInput[]
  connectOrCreate?: Prisma.PackImageCreateOrConnectWithoutImageInput | Prisma.PackImageCreateOrConnectWithoutImageInput[]
  createMany?: Prisma.PackImageCreateManyImageInputEnvelope
  connect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
}

export type PackImageUpdateManyWithoutImageNestedInput = {
  create?: Prisma.XOR<Prisma.PackImageCreateWithoutImageInput, Prisma.PackImageUncheckedCreateWithoutImageInput> | Prisma.PackImageCreateWithoutImageInput[] | Prisma.PackImageUncheckedCreateWithoutImageInput[]
  connectOrCreate?: Prisma.PackImageCreateOrConnectWithoutImageInput | Prisma.PackImageCreateOrConnectWithoutImageInput[]
  upsert?: Prisma.PackImageUpsertWithWhereUniqueWithoutImageInput | Prisma.PackImageUpsertWithWhereUniqueWithoutImageInput[]
  createMany?: Prisma.PackImageCreateManyImageInputEnvelope
  set?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  disconnect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  delete?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  connect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  update?: Prisma.PackImageUpdateWithWhereUniqueWithoutImageInput | Prisma.PackImageUpdateWithWhereUniqueWithoutImageInput[]
  updateMany?: Prisma.PackImageUpdateManyWithWhereWithoutImageInput | Prisma.PackImageUpdateManyWithWhereWithoutImageInput[]
  deleteMany?: Prisma.PackImageScalarWhereInput | Prisma.PackImageScalarWhereInput[]
}

export type PackImageUncheckedUpdateManyWithoutImageNestedInput = {
  create?: Prisma.XOR<Prisma.PackImageCreateWithoutImageInput, Prisma.PackImageUncheckedCreateWithoutImageInput> | Prisma.PackImageCreateWithoutImageInput[] | Prisma.PackImageUncheckedCreateWithoutImageInput[]
  connectOrCreate?: Prisma.PackImageCreateOrConnectWithoutImageInput | Prisma.PackImageCreateOrConnectWithoutImageInput[]
  upsert?: Prisma.PackImageUpsertWithWhereUniqueWithoutImageInput | Prisma.PackImageUpsertWithWhereUniqueWithoutImageInput[]
  createMany?: Prisma.PackImageCreateManyImageInputEnvelope
  set?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  disconnect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  delete?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  connect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  update?: Prisma.PackImageUpdateWithWhereUniqueWithoutImageInput | Prisma.PackImageUpdateWithWhereUniqueWithoutImageInput[]
  updateMany?: Prisma.PackImageUpdateManyWithWhereWithoutImageInput | Prisma.PackImageUpdateManyWithWhereWithoutImageInput[]
  deleteMany?: Prisma.PackImageScalarWhereInput | Prisma.PackImageScalarWhereInput[]
}

export type PackImageCreateNestedManyWithoutPackInput = {
  create?: Prisma.XOR<Prisma.PackImageCreateWithoutPackInput, Prisma.PackImageUncheckedCreateWithoutPackInput> | Prisma.PackImageCreateWithoutPackInput[] | Prisma.PackImageUncheckedCreateWithoutPackInput[]
  connectOrCreate?: Prisma.PackImageCreateOrConnectWithoutPackInput | Prisma.PackImageCreateOrConnectWithoutPackInput[]
  createMany?: Prisma.PackImageCreateManyPackInputEnvelope
  connect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
}

export type PackImageUncheckedCreateNestedManyWithoutPackInput = {
  create?: Prisma.XOR<Prisma.PackImageCreateWithoutPackInput, Prisma.PackImageUncheckedCreateWithoutPackInput> | Prisma.PackImageCreateWithoutPackInput[] | Prisma.PackImageUncheckedCreateWithoutPackInput[]
  connectOrCreate?: Prisma.PackImageCreateOrConnectWithoutPackInput | Prisma.PackImageCreateOrConnectWithoutPackInput[]
  createMany?: Prisma.PackImageCreateManyPackInputEnvelope
  connect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
}

export type PackImageUpdateManyWithoutPackNestedInput = {
  create?: Prisma.XOR<Prisma.PackImageCreateWithoutPackInput, Prisma.PackImageUncheckedCreateWithoutPackInput> | Prisma.PackImageCreateWithoutPackInput[] | Prisma.PackImageUncheckedCreateWithoutPackInput[]
  connectOrCreate?: Prisma.PackImageCreateOrConnectWithoutPackInput | Prisma.PackImageCreateOrConnectWithoutPackInput[]
  upsert?: Prisma.PackImageUpsertWithWhereUniqueWithoutPackInput | Prisma.PackImageUpsertWithWhereUniqueWithoutPackInput[]
  createMany?: Prisma.PackImageCreateManyPackInputEnvelope
  set?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  disconnect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  delete?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  connect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  update?: Prisma.PackImageUpdateWithWhereUniqueWithoutPackInput | Prisma.PackImageUpdateWithWhereUniqueWithoutPackInput[]
  updateMany?: Prisma.PackImageUpdateManyWithWhereWithoutPackInput | Prisma.PackImageUpdateManyWithWhereWithoutPackInput[]
  deleteMany?: Prisma.PackImageScalarWhereInput | Prisma.PackImageScalarWhereInput[]
}

export type PackImageUncheckedUpdateManyWithoutPackNestedInput = {
  create?: Prisma.XOR<Prisma.PackImageCreateWithoutPackInput, Prisma.PackImageUncheckedCreateWithoutPackInput> | Prisma.PackImageCreateWithoutPackInput[] | Prisma.PackImageUncheckedCreateWithoutPackInput[]
  connectOrCreate?: Prisma.PackImageCreateOrConnectWithoutPackInput | Prisma.PackImageCreateOrConnectWithoutPackInput[]
  upsert?: Prisma.PackImageUpsertWithWhereUniqueWithoutPackInput | Prisma.PackImageUpsertWithWhereUniqueWithoutPackInput[]
  createMany?: Prisma.PackImageCreateManyPackInputEnvelope
  set?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  disconnect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  delete?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  connect?: Prisma.PackImageWhereUniqueInput | Prisma.PackImageWhereUniqueInput[]
  update?: Prisma.PackImageUpdateWithWhereUniqueWithoutPackInput | Prisma.PackImageUpdateWithWhereUniqueWithoutPackInput[]
  updateMany?: Prisma.PackImageUpdateManyWithWhereWithoutPackInput | Prisma.PackImageUpdateManyWithWhereWithoutPackInput[]
  deleteMany?: Prisma.PackImageScalarWhereInput | Prisma.PackImageScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PackImageCreateWithoutImageInput = {
  id?: string
  weight?: number
  pack: Prisma.PackCreateNestedOneWithoutPackImagesInput
}

export type PackImageUncheckedCreateWithoutImageInput = {
  id?: string
  packId: string
  weight?: number
}

export type PackImageCreateOrConnectWithoutImageInput = {
  where: Prisma.PackImageWhereUniqueInput
  create: Prisma.XOR<Prisma.PackImageCreateWithoutImageInput, Prisma.PackImageUncheckedCreateWithoutImageInput>
}

export type PackImageCreateManyImageInputEnvelope = {
  data: Prisma.PackImageCreateManyImageInput | Prisma.PackImageCreateManyImageInput[]
}

export type PackImageUpsertWithWhereUniqueWithoutImageInput = {
  where: Prisma.PackImageWhereUniqueInput
  update: Prisma.XOR<Prisma.PackImageUpdateWithoutImageInput, Prisma.PackImageUncheckedUpdateWithoutImageInput>
  create: Prisma.XOR<Prisma.PackImageCreateWithoutImageInput, Prisma.PackImageUncheckedCreateWithoutImageInput>
}

export type PackImageUpdateWithWhereUniqueWithoutImageInput = {
  where: Prisma.PackImageWhereUniqueInput
  data: Prisma.XOR<Prisma.PackImageUpdateWithoutImageInput, Prisma.PackImageUncheckedUpdateWithoutImageInput>
}

export type PackImageUpdateManyWithWhereWithoutImageInput = {
  where: Prisma.PackImageScalarWhereInput
  data: Prisma.XOR<Prisma.PackImageUpdateManyMutationInput, Prisma.PackImageUncheckedUpdateManyWithoutImageInput>
}

export type PackImageScalarWhereInput = {
  AND?: Prisma.PackImageScalarWhereInput | Prisma.PackImageScalarWhereInput[]
  OR?: Prisma.PackImageScalarWhereInput[]
  NOT?: Prisma.PackImageScalarWhereInput | Prisma.PackImageScalarWhereInput[]
  id?: Prisma.StringFilter<"PackImage"> | string
  packId?: Prisma.StringFilter<"PackImage"> | string
  imageId?: Prisma.StringFilter<"PackImage"> | string
  weight?: Prisma.IntFilter<"PackImage"> | number
}

export type PackImageCreateWithoutPackInput = {
  id?: string
  weight?: number
  image: Prisma.ImageCreateNestedOneWithoutPackImagesInput
}

export type PackImageUncheckedCreateWithoutPackInput = {
  id?: string
  imageId: string
  weight?: number
}

export type PackImageCreateOrConnectWithoutPackInput = {
  where: Prisma.PackImageWhereUniqueInput
  create: Prisma.XOR<Prisma.PackImageCreateWithoutPackInput, Prisma.PackImageUncheckedCreateWithoutPackInput>
}

export type PackImageCreateManyPackInputEnvelope = {
  data: Prisma.PackImageCreateManyPackInput | Prisma.PackImageCreateManyPackInput[]
}

export type PackImageUpsertWithWhereUniqueWithoutPackInput = {
  where: Prisma.PackImageWhereUniqueInput
  update: Prisma.XOR<Prisma.PackImageUpdateWithoutPackInput, Prisma.PackImageUncheckedUpdateWithoutPackInput>
  create: Prisma.XOR<Prisma.PackImageCreateWithoutPackInput, Prisma.PackImageUncheckedCreateWithoutPackInput>
}

export type PackImageUpdateWithWhereUniqueWithoutPackInput = {
  where: Prisma.PackImageWhereUniqueInput
  data: Prisma.XOR<Prisma.PackImageUpdateWithoutPackInput, Prisma.PackImageUncheckedUpdateWithoutPackInput>
}

export type PackImageUpdateManyWithWhereWithoutPackInput = {
  where: Prisma.PackImageScalarWhereInput
  data: Prisma.XOR<Prisma.PackImageUpdateManyMutationInput, Prisma.PackImageUncheckedUpdateManyWithoutPackInput>
}

export type PackImageCreateManyImageInput = {
  id?: string
  packId: string
  weight?: number
}

export type PackImageUpdateWithoutImageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
  pack?: Prisma.PackUpdateOneRequiredWithoutPackImagesNestedInput
}

export type PackImageUncheckedUpdateWithoutImageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  packId?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackImageUncheckedUpdateManyWithoutImageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  packId?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackImageCreateManyPackInput = {
  id?: string
  imageId: string
  weight?: number
}

export type PackImageUpdateWithoutPackInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
  image?: Prisma.ImageUpdateOneRequiredWithoutPackImagesNestedInput
}

export type PackImageUncheckedUpdateWithoutPackInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imageId?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PackImageUncheckedUpdateManyWithoutPackInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  imageId?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.IntFieldUpdateOperationsInput | number
}



export type PackImageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  packId?: boolean
  imageId?: boolean
  weight?: boolean
  pack?: boolean | Prisma.PackDefaultArgs<ExtArgs>
  image?: boolean | Prisma.ImageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packImage"]>

export type PackImageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  packId?: boolean
  imageId?: boolean
  weight?: boolean
  pack?: boolean | Prisma.PackDefaultArgs<ExtArgs>
  image?: boolean | Prisma.ImageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packImage"]>

export type PackImageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  packId?: boolean
  imageId?: boolean
  weight?: boolean
  pack?: boolean | Prisma.PackDefaultArgs<ExtArgs>
  image?: boolean | Prisma.ImageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["packImage"]>

export type PackImageSelectScalar = {
  id?: boolean
  packId?: boolean
  imageId?: boolean
  weight?: boolean
}

export type PackImageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "packId" | "imageId" | "weight", ExtArgs["result"]["packImage"]>
export type PackImageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pack?: boolean | Prisma.PackDefaultArgs<ExtArgs>
  image?: boolean | Prisma.ImageDefaultArgs<ExtArgs>
}
export type PackImageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pack?: boolean | Prisma.PackDefaultArgs<ExtArgs>
  image?: boolean | Prisma.ImageDefaultArgs<ExtArgs>
}
export type PackImageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pack?: boolean | Prisma.PackDefaultArgs<ExtArgs>
  image?: boolean | Prisma.ImageDefaultArgs<ExtArgs>
}

export type $PackImagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PackImage"
  objects: {
    pack: Prisma.$PackPayload<ExtArgs>
    image: Prisma.$ImagePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    packId: string
    imageId: string
    weight: number
  }, ExtArgs["result"]["packImage"]>
  composites: {}
}

export type PackImageGetPayload<S extends boolean | null | undefined | PackImageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PackImagePayload, S>

export type PackImageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PackImageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PackImageCountAggregateInputType | true
  }

export interface PackImageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PackImage'], meta: { name: 'PackImage' } }
  /**
   * Find zero or one PackImage that matches the filter.
   * @param {PackImageFindUniqueArgs} args - Arguments to find a PackImage
   * @example
   * // Get one PackImage
   * const packImage = await prisma.packImage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PackImageFindUniqueArgs>(args: Prisma.SelectSubset<T, PackImageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PackImageClient<runtime.Types.Result.GetResult<Prisma.$PackImagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PackImage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PackImageFindUniqueOrThrowArgs} args - Arguments to find a PackImage
   * @example
   * // Get one PackImage
   * const packImage = await prisma.packImage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PackImageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PackImageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PackImageClient<runtime.Types.Result.GetResult<Prisma.$PackImagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PackImage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackImageFindFirstArgs} args - Arguments to find a PackImage
   * @example
   * // Get one PackImage
   * const packImage = await prisma.packImage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PackImageFindFirstArgs>(args?: Prisma.SelectSubset<T, PackImageFindFirstArgs<ExtArgs>>): Prisma.Prisma__PackImageClient<runtime.Types.Result.GetResult<Prisma.$PackImagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PackImage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackImageFindFirstOrThrowArgs} args - Arguments to find a PackImage
   * @example
   * // Get one PackImage
   * const packImage = await prisma.packImage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PackImageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PackImageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PackImageClient<runtime.Types.Result.GetResult<Prisma.$PackImagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PackImages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackImageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PackImages
   * const packImages = await prisma.packImage.findMany()
   * 
   * // Get first 10 PackImages
   * const packImages = await prisma.packImage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const packImageWithIdOnly = await prisma.packImage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PackImageFindManyArgs>(args?: Prisma.SelectSubset<T, PackImageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackImagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PackImage.
   * @param {PackImageCreateArgs} args - Arguments to create a PackImage.
   * @example
   * // Create one PackImage
   * const PackImage = await prisma.packImage.create({
   *   data: {
   *     // ... data to create a PackImage
   *   }
   * })
   * 
   */
  create<T extends PackImageCreateArgs>(args: Prisma.SelectSubset<T, PackImageCreateArgs<ExtArgs>>): Prisma.Prisma__PackImageClient<runtime.Types.Result.GetResult<Prisma.$PackImagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PackImages.
   * @param {PackImageCreateManyArgs} args - Arguments to create many PackImages.
   * @example
   * // Create many PackImages
   * const packImage = await prisma.packImage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PackImageCreateManyArgs>(args?: Prisma.SelectSubset<T, PackImageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PackImages and returns the data saved in the database.
   * @param {PackImageCreateManyAndReturnArgs} args - Arguments to create many PackImages.
   * @example
   * // Create many PackImages
   * const packImage = await prisma.packImage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PackImages and only return the `id`
   * const packImageWithIdOnly = await prisma.packImage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PackImageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PackImageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackImagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PackImage.
   * @param {PackImageDeleteArgs} args - Arguments to delete one PackImage.
   * @example
   * // Delete one PackImage
   * const PackImage = await prisma.packImage.delete({
   *   where: {
   *     // ... filter to delete one PackImage
   *   }
   * })
   * 
   */
  delete<T extends PackImageDeleteArgs>(args: Prisma.SelectSubset<T, PackImageDeleteArgs<ExtArgs>>): Prisma.Prisma__PackImageClient<runtime.Types.Result.GetResult<Prisma.$PackImagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PackImage.
   * @param {PackImageUpdateArgs} args - Arguments to update one PackImage.
   * @example
   * // Update one PackImage
   * const packImage = await prisma.packImage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PackImageUpdateArgs>(args: Prisma.SelectSubset<T, PackImageUpdateArgs<ExtArgs>>): Prisma.Prisma__PackImageClient<runtime.Types.Result.GetResult<Prisma.$PackImagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PackImages.
   * @param {PackImageDeleteManyArgs} args - Arguments to filter PackImages to delete.
   * @example
   * // Delete a few PackImages
   * const { count } = await prisma.packImage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PackImageDeleteManyArgs>(args?: Prisma.SelectSubset<T, PackImageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PackImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackImageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PackImages
   * const packImage = await prisma.packImage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PackImageUpdateManyArgs>(args: Prisma.SelectSubset<T, PackImageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PackImages and returns the data updated in the database.
   * @param {PackImageUpdateManyAndReturnArgs} args - Arguments to update many PackImages.
   * @example
   * // Update many PackImages
   * const packImage = await prisma.packImage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PackImages and only return the `id`
   * const packImageWithIdOnly = await prisma.packImage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PackImageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PackImageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackImagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PackImage.
   * @param {PackImageUpsertArgs} args - Arguments to update or create a PackImage.
   * @example
   * // Update or create a PackImage
   * const packImage = await prisma.packImage.upsert({
   *   create: {
   *     // ... data to create a PackImage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PackImage we want to update
   *   }
   * })
   */
  upsert<T extends PackImageUpsertArgs>(args: Prisma.SelectSubset<T, PackImageUpsertArgs<ExtArgs>>): Prisma.Prisma__PackImageClient<runtime.Types.Result.GetResult<Prisma.$PackImagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PackImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackImageCountArgs} args - Arguments to filter PackImages to count.
   * @example
   * // Count the number of PackImages
   * const count = await prisma.packImage.count({
   *   where: {
   *     // ... the filter for the PackImages we want to count
   *   }
   * })
  **/
  count<T extends PackImageCountArgs>(
    args?: Prisma.Subset<T, PackImageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PackImageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PackImage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackImageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PackImageAggregateArgs>(args: Prisma.Subset<T, PackImageAggregateArgs>): Prisma.PrismaPromise<GetPackImageAggregateType<T>>

  /**
   * Group by PackImage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PackImageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PackImageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PackImageGroupByArgs['orderBy'] }
      : { orderBy?: PackImageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PackImageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPackImageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PackImage model
 */
readonly fields: PackImageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PackImage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PackImageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pack<T extends Prisma.PackDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PackDefaultArgs<ExtArgs>>): Prisma.Prisma__PackClient<runtime.Types.Result.GetResult<Prisma.$PackPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  image<T extends Prisma.ImageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ImageDefaultArgs<ExtArgs>>): Prisma.Prisma__ImageClient<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PackImage model
 */
export interface PackImageFieldRefs {
  readonly id: Prisma.FieldRef<"PackImage", 'String'>
  readonly packId: Prisma.FieldRef<"PackImage", 'String'>
  readonly imageId: Prisma.FieldRef<"PackImage", 'String'>
  readonly weight: Prisma.FieldRef<"PackImage", 'Int'>
}
    

// Custom InputTypes
/**
 * PackImage findUnique
 */
export type PackImageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageInclude<ExtArgs> | null
  /**
   * Filter, which PackImage to fetch.
   */
  where: Prisma.PackImageWhereUniqueInput
}

/**
 * PackImage findUniqueOrThrow
 */
export type PackImageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageInclude<ExtArgs> | null
  /**
   * Filter, which PackImage to fetch.
   */
  where: Prisma.PackImageWhereUniqueInput
}

/**
 * PackImage findFirst
 */
export type PackImageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageInclude<ExtArgs> | null
  /**
   * Filter, which PackImage to fetch.
   */
  where?: Prisma.PackImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackImages to fetch.
   */
  orderBy?: Prisma.PackImageOrderByWithRelationInput | Prisma.PackImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PackImages.
   */
  cursor?: Prisma.PackImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PackImages.
   */
  distinct?: Prisma.PackImageScalarFieldEnum | Prisma.PackImageScalarFieldEnum[]
}

/**
 * PackImage findFirstOrThrow
 */
export type PackImageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageInclude<ExtArgs> | null
  /**
   * Filter, which PackImage to fetch.
   */
  where?: Prisma.PackImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackImages to fetch.
   */
  orderBy?: Prisma.PackImageOrderByWithRelationInput | Prisma.PackImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PackImages.
   */
  cursor?: Prisma.PackImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PackImages.
   */
  distinct?: Prisma.PackImageScalarFieldEnum | Prisma.PackImageScalarFieldEnum[]
}

/**
 * PackImage findMany
 */
export type PackImageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageInclude<ExtArgs> | null
  /**
   * Filter, which PackImages to fetch.
   */
  where?: Prisma.PackImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PackImages to fetch.
   */
  orderBy?: Prisma.PackImageOrderByWithRelationInput | Prisma.PackImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PackImages.
   */
  cursor?: Prisma.PackImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PackImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PackImages.
   */
  skip?: number
  distinct?: Prisma.PackImageScalarFieldEnum | Prisma.PackImageScalarFieldEnum[]
}

/**
 * PackImage create
 */
export type PackImageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageInclude<ExtArgs> | null
  /**
   * The data needed to create a PackImage.
   */
  data: Prisma.XOR<Prisma.PackImageCreateInput, Prisma.PackImageUncheckedCreateInput>
}

/**
 * PackImage createMany
 */
export type PackImageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PackImages.
   */
  data: Prisma.PackImageCreateManyInput | Prisma.PackImageCreateManyInput[]
}

/**
 * PackImage createManyAndReturn
 */
export type PackImageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * The data used to create many PackImages.
   */
  data: Prisma.PackImageCreateManyInput | Prisma.PackImageCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PackImage update
 */
export type PackImageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageInclude<ExtArgs> | null
  /**
   * The data needed to update a PackImage.
   */
  data: Prisma.XOR<Prisma.PackImageUpdateInput, Prisma.PackImageUncheckedUpdateInput>
  /**
   * Choose, which PackImage to update.
   */
  where: Prisma.PackImageWhereUniqueInput
}

/**
 * PackImage updateMany
 */
export type PackImageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PackImages.
   */
  data: Prisma.XOR<Prisma.PackImageUpdateManyMutationInput, Prisma.PackImageUncheckedUpdateManyInput>
  /**
   * Filter which PackImages to update
   */
  where?: Prisma.PackImageWhereInput
  /**
   * Limit how many PackImages to update.
   */
  limit?: number
}

/**
 * PackImage updateManyAndReturn
 */
export type PackImageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * The data used to update PackImages.
   */
  data: Prisma.XOR<Prisma.PackImageUpdateManyMutationInput, Prisma.PackImageUncheckedUpdateManyInput>
  /**
   * Filter which PackImages to update
   */
  where?: Prisma.PackImageWhereInput
  /**
   * Limit how many PackImages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PackImage upsert
 */
export type PackImageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageInclude<ExtArgs> | null
  /**
   * The filter to search for the PackImage to update in case it exists.
   */
  where: Prisma.PackImageWhereUniqueInput
  /**
   * In case the PackImage found by the `where` argument doesn't exist, create a new PackImage with this data.
   */
  create: Prisma.XOR<Prisma.PackImageCreateInput, Prisma.PackImageUncheckedCreateInput>
  /**
   * In case the PackImage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PackImageUpdateInput, Prisma.PackImageUncheckedUpdateInput>
}

/**
 * PackImage delete
 */
export type PackImageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageInclude<ExtArgs> | null
  /**
   * Filter which PackImage to delete.
   */
  where: Prisma.PackImageWhereUniqueInput
}

/**
 * PackImage deleteMany
 */
export type PackImageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PackImages to delete
   */
  where?: Prisma.PackImageWhereInput
  /**
   * Limit how many PackImages to delete.
   */
  limit?: number
}

/**
 * PackImage without action
 */
export type PackImageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackImage
   */
  select?: Prisma.PackImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackImage
   */
  omit?: Prisma.PackImageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackImageInclude<ExtArgs> | null
}
